### ISSUE TITLE
Sample app: Undefined liberty server http port

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/draft-iguide-retry-timeout#87]
# Problem
In message.log during `mvn install`
`[6/8/18 14:25:45:663 CDT] 00000018 com.ibm.ws.config.xml.internal.ConfigUpdater                 E CWWKG0075E: The value {default.http.port} is not valid for attribute httpPort of configuration element httpEndpoint. The validation message was: Value "{default.http.port}" is not a number..`

# server.xml 
- [x] httpPort="{default.http.port}" is missing "$"
- [x] Remove httpsPort because the ssl feature is not enabled
- [x] Remove unneeded feature `webProfile-7.0` to improve server performance

**Comment by kevinwlau** [comment]
These changes also apply to the step in the guide for enabling MicroProfile
